apiVersion: v2
description: A Helm chart to deploy Elasticsearch managed by the ECK Operator.
icon: https://helm.elastic.co/icons/elasticsearch.png
kubeVersion: '>= 1.21.0-0'
name: eck-elasticsearch
sources:
- https://github.com/elastic/cloud-on-k8s
- https://github.com/elastic/elasticsearch/
type: application
version: 0.2.0
