apiVersion: v2
description: A Helm chart to deploy Kibana managed by the ECK Operator.
icon: https://helm.elastic.co/icons/kibana.png
kubeVersion: '>= 1.21.0-0'
name: eck-kibana
sources:
- https://github.com/elastic/cloud-on-k8s
- https://github.com/elastic/kibana
type: application
version: 0.2.0
